### ISSUE TITLE
support sharing individual file

### ISSUE THREAD

**Issue by juliangruber** [datproject/dat-js#29]
something like this maybe?

```js
var dat = Dat({ file: path })
```

This is required as we want to allow people to share individual files through dat-desktop, where there might be other unrelated files in the same directory.

**Comment by juliangruber** [comment]
note that in this case, unless a custom `.db` option is provided, we must make sure there's no overlap between paths, so something like `./.dat-${file}` should work

**Comment by karissa** [comment]
I think we want to keep it as a folder instead of a file for now unless we restructure the design. Right now a .dat file is put in the folder which maintains a dat-folder relationship. 

If dat desktop one day wants to share single files it could use hyperdrive directly but I think we should wait on it in any case and get single folder watching and sharing to work really well first.

**Comment by juliangruber** [comment]
Dat desktop already supports sharing individual files, simply for convenience. For it to be practical, an interim solution would be to create an empty folder with the single file symlinked in somewhere.

**Comment by karissa** [comment]
see https://github.com/datproject/dat/issues/527 for now
